export type Exercise = {
  id: string; name: string; sets: number;
  reps?: string; duration?: number; rest: number;
  how: string; mistakes: string[]; image?: string;
};
export type WorkoutSection = {
  id: string; title: string; icon: string; color: string; exercises: Exercise[];
};
export type DayWorkout = {
  day: number; muscle: string; badge: string; color: string; sections: WorkoutSection[];
};

const WARMUP: WorkoutSection = {
  id:'warmup', title:'Pre-Workout Warmup', icon:'🌅', color:'#F5C842',
  exercises:[
    {id:'w1',name:'Arm Circles',sets:1,reps:'10 fwd + 10 back',rest:15,image:'/exercises/warmup.png',
      how:'Stand tall, extend arms sideways. Make small circles growing larger. 10 forward then 10 backward each arm. Feel the shoulder joint open up.',
      mistakes:['Rushing — go slow and deliberate','Tensing the neck — keep relaxed']},
    {id:'w2',name:'Shoulder Rolls',sets:1,reps:'10 each direction',rest:15,image:'/exercises/warmup.png',
      how:'Roll shoulders backward in large circles 10 times, then forward 10 times. Exaggerate the movement to mobilise the shoulder joint fully.',
      mistakes:['Going too fast — the slower the better','Not completing full circles']},
    {id:'w3',name:'Hip Circles',sets:1,reps:'10 each side',rest:15,image:'/exercises/warmup.png',
      how:'Hands on hips, feet shoulder-width. Draw large circles with your hips — 10 clockwise, 10 counter-clockwise. Loosen the hip flexors.',
      mistakes:['Small circles — go as big as possible','Moving shoulders instead of hips']},
    {id:'w4',name:'Leg Swings',sets:1,reps:'10 each leg',rest:15,image:'/exercises/warmup.png',
      how:'Stand sideways to a wall, one hand on wall for balance. Swing one leg forward and back in pendulum motion. 10 swings each leg.',
      mistakes:['Swinging too forcefully — controlled arc','Not holding something stable for balance']},
    {id:'w5',name:'Bodyweight Squat',sets:2,reps:'10 slow',rest:20,image:'/exercises/warmup.png',
      how:'Feet shoulder-width, toes slightly out. Squat slowly until thighs are parallel. Drive through heels to rise. Wakes up glutes and quads.',
      mistakes:['Heels rising off floor','Chest collapsing forward','Knees caving inward']},
  ]
};

const ABS_SECTION: WorkoutSection = {
  id:'abs', title:'Abs Circuit — 15 Min', icon:'🎯', color:'#00C7BE',
  exercises:[
    {id:'a1',name:'Standing DB Wood Chop',sets:3,reps:'15 each side',rest:20,image:'/exercises/abs.png',
      how:'Hold one DB with both hands. Rotate diagonally from high (shoulder) to low (opposite hip). Pivot the rear foot. Rotation comes from torso — arms just hold the weight.',
      mistakes:['Using arms only — torso must initiate the rotation','Not pivoting rear foot — limits range and puts stress on knees','Going too fast — each chop should be deliberate']},
    {id:'a2',name:'Standing DB Side Bend',sets:3,reps:'15 each side',rest:20,image:'/exercises/abs.png',
      how:'DB in one hand at side, other hand behind head. Bend directly sideways — pure lateral plane. Squeeze the opposite oblique hard. Return slowly under control.',
      mistakes:['Leaning forward or backward — must be pure lateral movement','Swinging the weight down with momentum','Not actually squeezing — just bending']},
    {id:'a3',name:'Standing DB Russian Twist',sets:3,reps:'15 each side',rest:20,image:'/exercises/abs.png',
      how:'Hold DB at chest with both hands. Feet hip-width, knees slightly soft. Rotate torso fully left then fully right. Hips stay square and face forward at all times.',
      mistakes:['Rotating hips instead of torso — hips must stay still','Going too fast — each rotation is deliberate and controlled','Feet too wide — closer stance forces more core engagement']},
    {id:'a4',name:'Standing DB Windmill',sets:3,reps:'15 each side',rest:20,image:'/exercises/abs.png',
      how:'Hold DB overhead in one arm, other arm free. Push hips to the same side as the raised arm. Slide the free hand down the opposite leg until you feel the stretch. Keep eyes on the DB.',
      mistakes:['Bending forward instead of directly to the side','Rushing — this is a slow, controlled stretch and crunch','Dropping the overhead arm — keep it vertical throughout']},
    {id:'a5',name:'Standing DB Halo',sets:3,reps:'15',rest:20,image:'/exercises/abs.png',
      how:'Hold DB vertically at chest. Circle it slowly around your head — lift up one side, across the back, down the other side and back. Core braced hard. No body sway.',
      mistakes:['Too heavy — this should be a light DB for control','Swaying your body to move the DB instead of moving arms','Tilting your head to follow the DB — keep head neutral']},
    {id:'a6',name:'Standing DB Overhead Crunch',sets:3,reps:'15',rest:20,image:'/exercises/abs.png',
      how:'Hold DB overhead with both hands, arms completely straight. Crunch your ribcage down toward your hips by contracting the upper abs. Arms stay straight throughout.',
      mistakes:['Bending elbows at the top — arms must stay straight','Hinging at hips instead of crunching from the core','Leaning backward — stay upright throughout']},
  ]
};

const COOLDOWN: WorkoutSection = {
  id:'cooldown', title:'Post-Workout Cooldown', icon:'🌊', color:'#64B4FF',
  exercises:[
    {id:'c1',name:"Child's Pose",sets:1,duration:45,rest:10,image:'/exercises/cooldown.png',
      how:'Kneel on floor, sit back toward heels, extend arms far forward on the floor. Let forehead rest down. Breathe deeply — in through nose, out through mouth. Hold 45-60 seconds.',
      mistakes:['Holding breath — deep continuous breathing is essential','Rushing through it — this needs the full time']},
    {id:'c2',name:'Chest & Shoulder Stretch',sets:1,duration:30,rest:10,image:'/exercises/cooldown.png',
      how:'Stand tall, open arms wide, palms facing up toward ceiling. Gently press your chest forward and squeeze shoulder blades together. Feel the stretch across the pecs and front shoulders.',
      mistakes:['Forcing too aggressively — gentle sustained stretch','Not breathing through it']},
    {id:'c3',name:'Hamstring Stretch',sets:1,duration:30,rest:10,image:'/exercises/cooldown.png',
      how:'Sit on floor, extend one leg straight. Reach toward your toes, hinging from the hips. Feel the back of the thigh. Hold — do not bounce. Switch legs.',
      mistakes:['Bouncing instead of holding the stretch','Rounding the spine completely — try to hinge from hips not waist']},
    {id:'c4',name:'Hip Flexor Stretch',sets:1,duration:30,rest:10,image:'/exercises/cooldown.png',
      how:'Lunge position with back knee resting on floor. Press hips forward and down into the floor. Feel the deep stretch at the front of the hip and thigh. Switch sides.',
      mistakes:['Not pressing hips forward — just standing in a lunge','Holding breath — breathe into the stretch']},
    {id:'c5',name:'Cat-Cow Spine',sets:1,reps:'10 each',rest:15,image:'/exercises/cooldown.png',
      how:'On all fours, wrists under shoulders, knees under hips. Inhale — arch spine down, head up (cow). Exhale — round spine up, head down (cat). One breath per movement.',
      mistakes:['Moving too fast — one full breath per movement','Not using full range of the spine — exaggerate both positions']},
  ]
};

const BACK_PAIN: WorkoutSection = {
  id:'backpain', title:'Back Pain Relief', icon:'🔄', color:'#8E8EFF',
  exercises:[
    {id:'b1',name:'Knee to Chest Hold',sets:1,duration:30,rest:10,image:'/exercises/backpain.png',
      how:'Lie flat on your back on a firm surface. Gently pull both knees toward your chest with your hands. Hold and breathe deeply for 30 seconds. This releases lower back compression.',
      mistakes:['Pulling too aggressively — gentle traction only','Holding breath — deep breathing amplifies the release']},
    {id:'b2',name:'Pelvic Tilt',sets:2,reps:'10 x 10-sec holds',rest:15,image:'/exercises/backpain.png',
      how:'Lie on back, knees bent, feet flat on floor. Gently flatten your lower back against the floor by tightening abs and tilting pelvis. Hold 10 seconds. Release. Repeat 10 times.',
      mistakes:['Pushing with glutes — use only core to create the tilt','Holding breath during the hold']},
    {id:'b3',name:'Bird Dog',sets:2,reps:'10 each side',rest:20,image:'/exercises/backpain.png',
      how:'On all fours, neutral spine. Extend right arm and left leg simultaneously until both are level with your body. Hold 5 seconds. Slowly return. Alternate sides. Keep hips completely level.',
      mistakes:['Rotating hips when extending — they must stay level throughout','Rushing without the 5-second hold — the hold is the point','Looking up — keep neck in neutral alignment with spine']},
    {id:'b4',name:'Piriformis Stretch',sets:1,duration:30,rest:10,image:'/exercises/backpain.png',
      how:'Lie on back. Cross right ankle over left knee, creating a figure-4 shape. Pull left thigh toward chest until you feel a deep stretch in the right buttock/hip. Hold. Switch sides.',
      mistakes:['Not feeling it deep in the glute — adjust ankle position higher on the knee','Raising head off floor — keep it relaxed down']},
    {id:'b5',name:"Child's Pose — Spine Decompress",sets:1,duration:60,rest:0,image:'/exercises/backpain.png',
      how:'Kneel and reach arms far forward on floor. Let the entire spine elongate naturally. Breathe deeply for 60 full seconds. Gravity gently decompresses the vertebrae.',
      mistakes:['Not staying for the full 60 seconds — the decompression takes time','Holding tension in shoulders — let them completely release']},
  ]
};

export const BRO_SPLIT: DayWorkout[] = [
  { day:1, muscle:'Chest', badge:'MON', color:'#FF6B35',
    sections:[ WARMUP,
      { id:'main', title:'Chest Workout', icon:'💪', color:'#FF6B35', exercises:[
        {id:'ch1',name:'DB Bench Press (Flat)',sets:3,reps:'12–15',rest:60,image:'/exercises/chest.png',
          how:'Lie flat on bench, feet planted firmly on floor. Lower DBs to chest level with elbows at 45° — not flared. Press up without fully locking out elbows. Control a 3-second negative on every rep.',
          mistakes:['Elbows flaring to 90° — major shoulder injury risk over time','Bouncing DBs off chest — removes tension and risks injury','Excessive lower back arch — keep a natural arch only']},
        {id:'ch2',name:'DB Incline Press',sets:3,reps:'12',rest:60,image:'/exercises/chest.png',
          how:'Set bench to 30-45°. Press from upper chest. Squeeze shoulder blades back and down throughout. Lower until a good stretch is felt in the upper pec.',
          mistakes:['Bench too steep (>45°) — load shifts entirely to shoulders','Not controlling the descent — loss of time under tension']},
        {id:'ch3',name:'DB Chest Fly',sets:3,reps:'12',rest:60,image:'/exercises/chest.png',
          how:'Lie flat, DBs above chest. Maintain a slight fixed bend in elbows — never straighten. Open arms wide in an arc until a deep pec stretch is felt. Squeeze pecs to bring DBs back together.',
          mistakes:['Turning into a press — elbows must stay fixed at the same angle throughout','Going too heavy — this is isolation, not a power movement']},
        {id:'ch4',name:'DB Decline Press',sets:3,reps:'12',rest:60,image:'/exercises/chest.png',
          how:'Lower bench angle for lower chest emphasis. Elbows stay at 45°. Press up, core stays tight for stability on the decline angle.',
          mistakes:['DBs drifting too wide apart at the top — keep them close','Rushing reps — use full controlled range of motion']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:2, muscle:'Back', badge:'TUE', color:'#34C759',
    sections:[ WARMUP,
      { id:'main', title:'Back Workout', icon:'🏋️', color:'#34C759', exercises:[
        {id:'bk1',name:'Pull-ups (Wide Grip)',sets:3,reps:'Max reps',rest:90,image:'/exercises/back.png',
          how:'Grip bar wider than shoulders. Pull chest toward the bar — not just chin. Squeeze shoulder blades together at the top. Full dead hang at the bottom every rep. Strict form only.',
          mistakes:['Kipping or swinging — strict reps only, always','Not reaching full hang at bottom — partial reps build less','Pulling with biceps, not engaging the lats — think elbows to back pockets']},
        {id:'bk2',name:'DB Bent-over Row',sets:3,reps:'12 per arm',rest:60,image:'/exercises/back.png',
          how:'Hinge at hips to 45°, maintain neutral spine throughout. Drive elbow straight back past hip. Hold 1 second at top — squeeze the lat. Lower slowly over 3 seconds.',
          mistakes:['Rounding lower back — the single biggest injury risk','Jerking weight up with momentum — controlled movement only','Rotating torso with each rep — torso stays still']},
        {id:'bk3',name:'DB Single-arm Row',sets:3,reps:'12 per arm',rest:60,image:'/exercises/back.png',
          how:'Place knee and hand on bench for support. Pull DB to hip — not shoulder. Think "elbow to ceiling." Arm fully extends at the bottom before each pull.',
          mistakes:['Pulling too high toward shoulder — uses rear delt not lat','Not stabilising with the support arm properly']},
        {id:'bk4',name:'DB Reverse Fly',sets:3,reps:'15',rest:60,image:'/exercises/back.png',
          how:'Bend forward to 90°. Arms with a slight bend — never fully straight. Raise both arms sideways to shoulder height, leading with the elbows. Targets rear delts and upper back.',
          mistakes:['Too heavy — control is everything on this exercise','Straightening arms fully — the soft bend must be maintained']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:3, muscle:'Shoulders', badge:'WED', color:'#AF52DE',
    sections:[ WARMUP,
      { id:'main', title:'Shoulder Workout', icon:'🎯', color:'#AF52DE', exercises:[
        {id:'sh1',name:'DB Overhead Press',sets:3,reps:'12',rest:60,image:'/exercises/shoulders.png',
          how:'Start with DBs at shoulder height, palms facing forward. Press straight up. Bring DBs slightly together at the top. Lower to ear level. Core braced throughout.',
          mistakes:['Flaring elbows too wide — reduces shoulder efficiency','Hip thrust to assist the press — core keeps you upright','Partial reps — must go fully overhead every rep']},
        {id:'sh2',name:'DB Lateral Raise',sets:3,reps:'15',rest:60,image:'/exercises/shoulders.png',
          how:'Slight elbow bend that is fixed. Raise arms to shoulder height leading with elbows — not hands. Pause 1 second at the top. Pull shoulders DOWN before starting — no shrugging.',
          mistakes:['Shrugging traps to help raise — pull shoulders down first','Going heavy and swinging — you should feel burn in the side delt','Raising above shoulder height — no added benefit for the lateral head']},
        {id:'sh3',name:'DB Front Raise',sets:3,reps:'12',rest:60,image:'/exercises/shoulders.png',
          how:'Alternating arms or together. Raise to shoulder height only with thumbs slightly up. Control the full descent. No swinging.',
          mistakes:['Swinging body backward to assist the lift','Going above shoulder height — no added benefit']},
        {id:'sh4',name:'DB Arnold Press',sets:3,reps:'12',rest:60,image:'/exercises/shoulders.png',
          how:'Start with DBs at chin height, palms facing you. As you press up, rotate palms to face outward. Reverse the full rotation on the descent. Complete rotation on every single rep.',
          mistakes:['Rushing the rotation — slow and deliberate on both up and down','Partial range of motion — full rotation is the whole point']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:4, muscle:'Legs', badge:'THU', color:'#FFD60A',
    sections:[ WARMUP,
      { id:'main', title:'Leg Workout', icon:'🦵', color:'#FFD60A', exercises:[
        {id:'lg1',name:'DB Goblet Squat',sets:3,reps:'15',rest:60,image:'/exercises/legs.png',
          how:'Hold DB vertically at chest. Feet shoulder-width, toes slightly out. Squat deep — thighs at parallel or below. Chest stays tall throughout. Drive through heels to stand.',
          mistakes:['Heels rising off floor — go lighter or elevate heels slightly','Knees caving inward — push knees actively out over toes','Forward lean — chest must stay tall throughout']},
        {id:'lg2',name:'DB Romanian Deadlift',sets:3,reps:'12',rest:60,image:'/exercises/legs.png',
          how:'Hold DBs in front of thighs. Hinge at hips — push hips back while keeping legs mostly straight. Lower DBs along the legs until you feel a strong hamstring stretch. Drive hips forward to return.',
          mistakes:['Rounding lower back — the most critical mistake on this exercise','Bending knees too much — this is a hip hinge, not a squat','DBs swinging away from legs — they stay close throughout']},
        {id:'lg3',name:'DB Walking Lunge',sets:3,reps:'10 each leg',rest:60,image:'/exercises/legs.png',
          how:'Step forward, lower back knee to near the floor. Front shin stays vertical — key alignment point. Push off the front foot to step into the next lunge.',
          mistakes:['Front knee shooting past toes — front shin must stay vertical','Torso leaning too far forward — stay upright','Short steps that create knee stress — take a long stride']},
        {id:'lg4',name:'DB Calf Raise',sets:3,reps:'20',rest:45,image:'/exercises/legs.png',
          how:'Stand on edge of step if available. Full range — lower until a deep calf stretch is felt. Rise to full contraction, squeeze and hold 1 second at the top.',
          mistakes:['Partial reps — calves only grow with full stretch and contraction','Going too fast — slow deliberate reps are more effective']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:5, muscle:'Biceps', badge:'FRI', color:'#FF2D55',
    sections:[ WARMUP,
      { id:'main', title:'Biceps Workout', icon:'💪', color:'#FF2D55', exercises:[
        {id:'bi1',name:'DB Standing Bicep Curl',sets:3,reps:'12',rest:60,image:'/exercises/biceps.png',
          how:'Stand tall. Elbows pinned firmly to side ribs — they must not move. Curl both DBs together, supinating (rotating palms fully up) at the top for peak contraction. Lower slowly — 3 full seconds.',
          mistakes:['Swinging body to lift — elbows are fixed, body is still','Not fully supinating at the top — you lose peak bicep contraction','Dropping the weight down quickly — the negative is where muscle is built']},
        {id:'bi2',name:'DB Hammer Curl',sets:3,reps:'12',rest:60,image:'/exercises/biceps.png',
          how:'Neutral grip — palms face each other — maintained throughout the entire movement. No rotation. Targets the brachialis muscle that sits under the bicep. Key for arm width and thickness.',
          mistakes:['Rotating wrist during the curl — keep the neutral grip the entire way','Swinging elbows forward off the sides of the body']},
        {id:'bi3',name:'DB Concentration Curl',sets:3,reps:'12 per arm',rest:60,image:'/exercises/biceps.png',
          how:'Sit on bench, elbow resting on inner thigh as a fixed brace. Curl slowly, squeeze hard at the top, lower to full extension. The thigh prevents any swing — zero momentum possible.',
          mistakes:['Using thigh to push the elbow up — it is a brace, not a helper','Short range of motion — always go to full arm extension at the bottom']},
        {id:'bi4',name:'DB Incline Curl',sets:3,reps:'12',rest:60,image:'/exercises/biceps.png',
          how:'Sit on incline bench at 45°. Let arms hang straight down in a fully stretched position. Curl from this stretched starting position for maximum long-head bicep activation.',
          mistakes:['Bench too upright — defeats the purpose of the stretched starting position','Swinging elbows forward off the bench during the curl']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:6, muscle:'Triceps', badge:'SAT', color:'#FF9500',
    sections:[ WARMUP,
      { id:'main', title:'Triceps Workout', icon:'🔱', color:'#FF9500', exercises:[
        {id:'tr1',name:'DB Overhead Tricep Extension',sets:3,reps:'12',rest:60,image:'/exercises/triceps.png',
          how:'Hold one DB overhead with both hands clasped around the top. Lower behind head by bending ONLY at the elbows. Upper arms stay vertical and completely still. Press back up to full extension.',
          mistakes:['Elbows flaring out wide — they must point straight forward throughout','Moving the upper arms — only the forearms should move','Not going to full range behind the head — partial reps limit results']},
        {id:'tr2',name:'DB Tricep Kickback',sets:3,reps:'15 per arm',rest:60,image:'/exercises/triceps.png',
          how:'Hinge forward at hips with a flat back. Upper arm is parallel to the floor and stays locked there. Extend the forearm backward to full lockout. Squeeze at the fully extended position.',
          mistakes:['Upper arm drooping downward during the movement — must stay parallel','Swinging the arm with momentum instead of controlled extension','Not reaching full lockout — cut range of motion cuts results']},
        {id:'tr3',name:'DB Close-grip Press',sets:3,reps:'12',rest:60,image:'/exercises/triceps.png',
          how:'Lie on bench, DBs close together with palms facing each other. Press up while keeping elbows tucked close to the sides of your body throughout the entire press.',
          mistakes:['Elbows flaring out — it becomes a chest press, not a tricep press','DBs drifting apart at the top of the movement']},
        {id:'tr4',name:'DB Skull Crusher',sets:3,reps:'10',rest:60,image:'/exercises/triceps.png',
          how:'Lie on bench, arms extended over chest. Bend ONLY at the elbows, lowering DBs toward temples. Elbows point toward ceiling throughout. Press back to start. Go lighter than you think.',
          mistakes:['Moving the upper arms forward — only the elbows should hinge','Going too heavy — puts enormous strain on elbow joints if form breaks']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:7, muscle:'Forearms', badge:'SUN', color:'#30D158',
    sections:[ WARMUP,
      { id:'main', title:'Forearm Workout', icon:'🤜', color:'#30D158', exercises:[
        {id:'fw1',name:'DB Wrist Curl (Palms Up)',sets:3,reps:'20',rest:45,image:'/exercises/forearms.png',
          how:'Sit, forearm resting fully on thigh, palm facing up, hand hanging off the knee. Curl wrist upward fully. Lower completely to a full open position. Full range every single rep.',
          mistakes:['Moving the whole forearm — only the wrist should move','Going too heavy — forearms respond to reps, not to heavy loads']},
        {id:'fw2',name:'DB Wrist Extension (Palms Down)',sets:3,reps:'20',rest:45,image:'/exercises/forearms.png',
          how:'Same position as wrist curl, but palm facing DOWN. Extend wrist upward. Targets the extensor muscles on the top of the forearm — commonly neglected, causing forearm imbalance.',
          mistakes:['Neglecting this side — extensor weakness causes tennis elbow over time','Not achieving full range — wrist must drop down completely between reps']},
        {id:'fw3',name:'DB Hammer Curl',sets:3,reps:'15',rest:60,image:'/exercises/forearms.png',
          how:'Standing, neutral grip throughout. Slow and controlled — no swinging. Targets the brachioradialis, the thick outer forearm muscle that creates the full forearm look.',
          mistakes:['Swinging body for momentum','Not going to full arm extension at the bottom of each rep']},
        {id:'fw4',name:"DB Farmer's Carry",sets:3,duration:30,rest:45,image:'/exercises/forearms.png',
          how:'Hold the heaviest DBs you can manage at sides. Walk with tall posture — shoulders back, chest up. Grip as hard as humanly possible for the entire 30 seconds. The king of forearm and grip strength.',
          mistakes:['Leaning to one side due to asymmetric grip strength','Letting DBs rest or bounce against the thighs during walking']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },
];

export const PPL_SPLIT: DayWorkout[] = [
  { day:1, muscle:'Push', badge:'DAY 1', color:'#FF6B35',
    sections:[ WARMUP,
      { id:'main', title:'Push — Chest, Shoulders & Triceps', icon:'💪', color:'#FF6B35', exercises:[
        {id:'p1',name:'DB Bench Press',sets:3,reps:'12',rest:60,image:'/exercises/push.png',
          how:'Lie flat on bench. Lower DBs to chest with elbows at 45°. Press up without full lockout. 3-second controlled descent.',
          mistakes:['Elbows flaring to 90°','Bouncing off chest','Excessive arch']},
        {id:'p2',name:'DB Overhead Press',sets:3,reps:'12',rest:60,image:'/exercises/shoulders.png',
          how:'Start at shoulders, palms forward. Press straight up. Core braced. Lower to ear level. Full range every rep.',
          mistakes:['Hip thrust to assist','Partial reps','Elbows too wide']},
        {id:'p3',name:'DB Lateral Raise',sets:3,reps:'15',rest:45,image:'/exercises/shoulders.png',
          how:'Lead with elbows to shoulder height. Pause 1 sec. Shoulders pulled DOWN — no shrugging ever.',
          mistakes:['Shrugging traps','Swinging with heavy weight','Above shoulder height']},
        {id:'p4',name:'DB Tricep Overhead Extension',sets:3,reps:'12',rest:60,image:'/exercises/triceps.png',
          how:'DB overhead both hands. Lower behind head — only elbows bend. Upper arms stay vertical and still.',
          mistakes:['Elbows flaring out','Moving upper arms','Partial range']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:2, muscle:'Pull', badge:'DAY 2', color:'#34C759',
    sections:[ WARMUP,
      { id:'main', title:'Pull — Back & Biceps', icon:'🏋️', color:'#34C759', exercises:[
        {id:'pl1',name:'Pull-ups',sets:3,reps:'Max reps',rest:90,image:'/exercises/pull.png',
          how:'Wide grip, pull chest to bar, squeeze shoulder blades. Full dead hang at the bottom. Strict form — no kipping.',
          mistakes:['Kipping','Partial range','Using arms not lats']},
        {id:'pl2',name:'DB Bent-over Row',sets:3,reps:'12 each arm',rest:60,image:'/exercises/back.png',
          how:'Hinge 45°, drive elbow past hip, hold 1 sec at top, 3-sec negative on descent.',
          mistakes:['Rounding back','Jerking weight','Torso rotation']},
        {id:'pl3',name:'DB Bicep Curl',sets:3,reps:'12',rest:60,image:'/exercises/biceps.png',
          how:'Elbows pinned to sides. Supinate fully at top. 3-second negative. No body swing.',
          mistakes:['Body swing','Not supinating at top','Rushing the negative']},
        {id:'pl4',name:'DB Hammer Curl',sets:3,reps:'12',rest:60,image:'/exercises/biceps.png',
          how:'Neutral grip throughout. Alternating arms. Targets brachialis for arm thickness.',
          mistakes:['Rotating wrist','Swinging elbows forward']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:3, muscle:'Legs', badge:'DAY 3', color:'#FFD60A',
    sections:[ WARMUP,
      { id:'main', title:'Legs — Quads, Hamstrings & Calves', icon:'🦵', color:'#FFD60A', exercises:[
        {id:'ll1',name:'DB Goblet Squat',sets:3,reps:'15',rest:60,image:'/exercises/legs.png',
          how:'DB at chest, squat below parallel, chest tall, knees tracking over toes throughout.',
          mistakes:['Heels rising','Knees caving in','Forward lean']},
        {id:'ll2',name:'DB Romanian Deadlift',sets:3,reps:'12',rest:60,image:'/exercises/legs.png',
          how:'Hip hinge — push hips back. Lower DBs along legs to hamstring stretch. Drive hips forward to return.',
          mistakes:['Rounding lower back','Too much knee bend','DBs swinging out']},
        {id:'ll3',name:'DB Walking Lunge',sets:3,reps:'10 each',rest:60,image:'/exercises/legs.png',
          how:'Front shin vertical. Back knee near floor. Push off and step forward into next lunge.',
          mistakes:['Front knee past toes','Torso leaning forward','Short steps']},
        {id:'ll4',name:'DB Calf Raise',sets:3,reps:'20',rest:45,image:'/exercises/legs.png',
          how:'Full range. Deep stretch down. Squeeze and hold at top 1 second. Slow is better.',
          mistakes:['Partial reps','Going too fast']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:4, muscle:'Push+', badge:'DAY 4', color:'#FF9500',
    sections:[ WARMUP,
      { id:'main', title:'Push 2 — Incline & Arm Focus', icon:'💪', color:'#FF9500', exercises:[
        {id:'p21',name:'DB Incline Press',sets:4,reps:'10',rest:75,image:'/exercises/chest.png',
          how:'Bench at 30-45°. Press from upper chest. Shoulder blades squeezed back throughout. 3-sec negative.',
          mistakes:['Bench too steep','Not controlling descent']},
        {id:'p22',name:'DB Arnold Press',sets:3,reps:'12',rest:60,image:'/exercises/shoulders.png',
          how:'Start palms facing you. Rotate outward as you press up. Full rotation every rep — both up and down.',
          mistakes:['Rushing the rotation','Partial range']},
        {id:'p23',name:'DB Chest Fly',sets:3,reps:'12',rest:60,image:'/exercises/chest.png',
          how:'Fixed elbow bend throughout. Arc motion, feel pec stretch wide, squeeze hard at top.',
          mistakes:['Turning into a press','Too heavy for isolation']},
        {id:'p24',name:'DB Tricep Kickback',sets:3,reps:'15 each',rest:45,image:'/exercises/triceps.png',
          how:'Hinge forward. Upper arm parallel to floor and locked. Extend to full lockout. Squeeze.',
          mistakes:['Upper arm drooping','Swinging for momentum']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:5, muscle:'Pull+', badge:'DAY 5', color:'#AF52DE',
    sections:[ WARMUP,
      { id:'main', title:'Pull 2 — Thickness & Arms', icon:'🏋️', color:'#AF52DE', exercises:[
        {id:'pl21',name:'Chin-ups',sets:3,reps:'Max reps',rest:90,image:'/exercises/pull.png',
          how:'Underhand grip, shoulder-width. Pull chest to bar. 3-sec descent. Full range always.',
          mistakes:['Kipping','Chin only — pull chest to bar','Rushing the descent']},
        {id:'pl22',name:'DB Single-arm Row',sets:3,reps:'12 each',rest:60,image:'/exercises/back.png',
          how:'Knee and hand on bench. Elbow to ceiling. Arm fully extended at bottom before each rep.',
          mistakes:['Pulling toward shoulder','Torso rotation']},
        {id:'pl23',name:'DB Concentration Curl',sets:3,reps:'12 each',rest:60,image:'/exercises/biceps.png',
          how:'Elbow on thigh, squeeze hard at top, full extension at bottom. Zero swing possible.',
          mistakes:['Thigh pushing elbow','Short range']},
        {id:'pl24',name:'DB Zottman Curl',sets:3,reps:'10',rest:60,image:'/exercises/biceps.png',
          how:'Curl up with palms up, rotate to palms down at top, lower with palms down. Hits biceps and forearms together.',
          mistakes:['Rotating too early — wait until fully curled','Going too heavy']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:6, muscle:'Legs+', badge:'DAY 6', color:'#30D158',
    sections:[ WARMUP,
      { id:'main', title:'Legs 2 — Power & Unilateral', icon:'🦵', color:'#30D158', exercises:[
        {id:'ll21',name:'DB Bulgarian Split Squat',sets:4,reps:'8 each leg',rest:90,image:'/exercises/legs.png',
          how:'Rear foot on bench, front foot far forward. Lower until front thigh is parallel to floor. Go lighter — this is very challenging even with light weight.',
          mistakes:['Front foot too close — knee shoots past toes','Dropping too fast — 2-3 sec controlled descent']},
        {id:'ll22',name:'DB Romanian Deadlift',sets:4,reps:'10',rest:75,image:'/exercises/legs.png',
          how:'Heavier than previous leg day. Hold 1 sec at the bottom in the hamstring stretch.',
          mistakes:['Rounding back at heavier weight','Losing the hip hinge — turning it into a squat']},
        {id:'ll23',name:'DB Goblet Squat',sets:3,reps:'12',rest:60,image:'/exercises/legs.png',
          how:'3-sec descent, explosive rise. Heavier DB than last time. Full depth every rep.',
          mistakes:['Speeding on descent — slow removes tension','Heels rising under heavier load']},
        {id:'ll24',name:'DB Single-leg Calf Raise',sets:3,reps:'15 each',rest:45,image:'/exercises/legs.png',
          how:'Hold same-side DB. Light touch on wall for balance only. Full range — calf does all the work.',
          mistakes:['Using wall to assist the lift','Half reps under load']},
      ]}, ABS_SECTION, COOLDOWN, BACK_PAIN ] },

  { day:7, muscle:'Active Rest', badge:'DAY 7', color:'#636366',
    sections:[ WARMUP,
      { id:'main', title:'Active Recovery', icon:'🌿', color:'#636366', exercises:[
        {id:'ar1',name:'20–30 Min Easy Walk',sets:1,duration:1200,rest:0,
          how:'Easy-paced walk outdoors or on treadmill. Focus on breathing. This is not a workout — it is movement that aids recovery by increasing blood flow to muscles.',
          mistakes:['Going too fast — this should feel effortless','Skipping it — movement aids recovery significantly']},
      ]}, COOLDOWN, BACK_PAIN ] },
];
